from __future__ import annotations
import argparse
import yaml

from pathlib import Path
from typing import Optional

import numpy as np
import torch
from torch.utils.data import DataLoader, TensorDataset

from src.models.hdeg.dbrl import DBRL
from src.utils.seed import set_seed
from src.utils.device import get_device
from src.utils.get_folders_utils import get_processed_folder

# ---------------------------------------------------------------------
# Supported preprocessing/window splits
# ---------------------------------------------------------------------

SPLITS = (
    "train",
    "val",
    "actor2_test",
    "actor1_test",
)


# ---------------------------------------------------------------------
# Window artifact loading
# ---------------------------------------------------------------------

def load_window_artifact(
    windows_dir: Path,
    split: str,
) -> dict[str, np.ndarray]:
    """
    Load one window artifact generated by prepare_windows.py.

    Expected arrays:

        X
        y
        window_start_timestamps
        target_timestamps
        window_size
        num_devices
    """

    path = Path(f"{windows_dir}/{split}.npz")

    if not path.is_file():
        raise FileNotFoundError(
            f"Window artifact not found:\n{path}"
        )

    with np.load(
        path,
        allow_pickle=False,
    ) as archive:

        required = (
            "X",
            "y",
            "window_start_timestamps",
            "target_timestamps",
            "window_size",
            "num_devices",
        )

        missing = [
            key
            for key in required
            if key not in archive.files
        ]

        if missing:
            raise KeyError(
                f"Window artifact {path} is missing "
                f"required entries: {missing}"
            )

        result = {
            key: archive[key].copy()
            for key in required
        }

    return result


# ---------------------------------------------------------------------
# Window artifact validation
# ---------------------------------------------------------------------

def validate_window_artifact(
    artifact: dict[str, np.ndarray],
) -> tuple[int, int, int]:
    """
    Validate the prepared-window artifact.

    Returns
    -------
    tuple
        (num_samples, window_size, num_devices)
    """

    X = artifact["X"]
    y = artifact["y"]

    window_start_timestamps = (
        artifact["window_start_timestamps"]
    )

    target_timestamps = (
        artifact["target_timestamps"]
    )

    window_size = int(
        artifact["window_size"]
    )

    num_devices = int(
        artifact["num_devices"]
    )

    # -------------------------------------------------------------
    # X
    # -------------------------------------------------------------

    if X.ndim != 3:
        raise ValueError(
            "X must have shape "
            "(num_samples, window_size, num_devices). "
            f"Received {X.shape}."
        )

    num_samples, actual_window_size, actual_num_devices = (
        X.shape
    )

    if num_samples <= 0:
        raise ValueError(
            "The window artifact contains no samples."
        )

    if actual_window_size != window_size:
        raise ValueError(
            "Window-size metadata mismatch: "
            f"metadata={window_size}, "
            f"X.shape[1]={actual_window_size}."
        )

    if actual_num_devices != num_devices:
        raise ValueError(
            "Device-count metadata mismatch: "
            f"metadata={num_devices}, "
            f"X.shape[2]={actual_num_devices}."
        )

    if not np.issubdtype(X.dtype, np.floating):
        raise TypeError(
            f"X must contain floating-point values. "
            f"Received dtype={X.dtype}."
        )

    if not np.isfinite(X).all():
        raise ValueError(
            "X contains NaN or infinite values."
        )

    # -------------------------------------------------------------
    # y
    # -------------------------------------------------------------

    expected_y_shape = (
        num_samples,
        num_devices,
    )

    if y.shape != expected_y_shape:
        raise ValueError(
            "Unexpected target shape. "
            f"Expected {expected_y_shape}, "
            f"received {y.shape}."
        )

    if not np.issubdtype(y.dtype, np.floating):
        raise TypeError(
            f"y must contain floating-point values. "
            f"Received dtype={y.dtype}."
        )

    if not np.isfinite(y).all():
        raise ValueError(
            "y contains NaN or infinite values."
        )

    # -------------------------------------------------------------
    # timestamps
    # -------------------------------------------------------------

    if len(window_start_timestamps) != num_samples:
        raise ValueError(
            "window_start_timestamps length does not "
            "match the number of samples."
        )

    if len(target_timestamps) != num_samples:
        raise ValueError(
            "target_timestamps length does not "
            "match the number of samples."
        )

    return (
        num_samples,
        window_size,
        num_devices,
    )


# ---------------------------------------------------------------------
# DBRL model construction
# ---------------------------------------------------------------------

def build_dbrl(
    *,
    hidden_dim: int,
    embedding_dim: int,
    gru_layers: int,
    graph_top_k: int,
    graph_self_loops: bool,
    graph_symmetric: bool,
    graph_heads: int,
    num_devices: int,
) -> DBRL:
    """
    Construct the DBRL module.

    This function deliberately contains no training logic.
    """

    if graph_self_loops:
        max_top_k = num_devices
    else:
        max_top_k = num_devices - 1

    if graph_top_k <= 0:
        raise ValueError(
            "graph_top_k must be greater than zero."
        )

    if graph_top_k > max_top_k:
        raise ValueError(
            f"graph_top_k={graph_top_k} is invalid for "
            f"N={num_devices} devices. "
            f"Maximum allowed value is {max_top_k} "
            f"with graph_self_loops="
            f"{graph_self_loops}."
        )

    model = DBRL(
        hidden_dim=hidden_dim,
        embedding_dim=embedding_dim,
        gru_layers=gru_layers,
        dropout=0.0,
        graph_top_k=graph_top_k,
        graph_self_loops=graph_self_loops,
        graph_symmetric=graph_symmetric,
        graph_heads=graph_heads,
        graph_dropout=0.0,
    )

    return model


# ---------------------------------------------------------------------
# DBRL forward execution
# ---------------------------------------------------------------------

def run_dbrl(
    model: DBRL,
    dataloader: DataLoader,
    device: torch.device,
    embedding_dim: int,
    num_devices: int,
    max_batches: Optional[int],
) -> torch.Tensor:
    """
    Execute DBRL in inference mode.

    Returns
    -------
    torch.Tensor
        Concatenated representations with shape:

            (num_processed_samples, N, D)
    """

    representations = []

    model.eval()

    with torch.no_grad():

        for batch_idx, batch in enumerate(
            dataloader
        ):

            # TensorDataset contains X and y.
            #
            # DBRL receives X only.
            x = batch[0].to(device)

            # -----------------------------------------------------
            # Input contract
            # -----------------------------------------------------

            if x.ndim != 3:
                raise RuntimeError(
                    "DBRL input must have three dimensions "
                    "(B, W, N). "
                    f"Received {tuple(x.shape)}."
                )

            batch_size, window_size, batch_devices = (
                x.shape
            )

            if batch_devices != num_devices:
                raise RuntimeError(
                    "Unexpected device dimension in batch. "
                    f"Expected N={num_devices}, "
                    f"received N={batch_devices}."
                )

            print(
                f"Batch {batch_idx + 1}: "
                f"X={tuple(x.shape)}",
                end="",
            )

            # -----------------------------------------------------
            # DBRL
            # -----------------------------------------------------

            z = model(x)

            print(
                f" -> Z={tuple(z.shape)}"
            )

            # -----------------------------------------------------
            # Output contract
            # -----------------------------------------------------

            expected_shape = (
                batch_size,
                num_devices,
                embedding_dim,
            )

            if z.shape != expected_shape:
                raise RuntimeError(
                    "DBRL output shape mismatch. "
                    f"Expected {expected_shape}, "
                    f"received {tuple(z.shape)}."
                )

            if not torch.isfinite(z).all():
                raise RuntimeError(
                    f"DBRL produced NaN or infinite values "
                    f"in batch {batch_idx}."
                )

            representations.append(
                z.detach().cpu()
            )

            if (
                max_batches is not None
                and batch_idx + 1 >= max_batches
            ):
                print()
                print(
                    f"Stopping after {max_batches} batch(es)."
                )
                break

    if not representations:
        raise RuntimeError(
            "DBRL produced no representations."
        )

    return torch.cat(
        representations,
        dim=0,
    )


# ---------------------------------------------------------------------
# Output saving
# ---------------------------------------------------------------------

def save_representations(
    output_path: Path,
    representations: torch.Tensor,
    *,
    split: str,
    window_size: int,
    num_devices: int,
    embedding_dim: int,
    batch_size: int,
    seed: int,
    overwrite: bool,
) -> None:

    if output_path.exists() and not overwrite:
        raise FileExistsError(
            f"Output file already exists:\n"
            f"{output_path}\n\n"
            "Use --overwrite to replace it."
        )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    payload = {
        "representations": representations,
        "split": split,
        "window_size": window_size,
        "num_devices": num_devices,
        "embedding_dim": embedding_dim,
        "batch_size": batch_size,
        "seed": seed,
    }

    torch.save(
        payload,
        output_path,
    )


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def main() -> None:
    # 1. Load config
    with open("configs/config.yaml") as f:
        config = yaml.safe_load(f)
        
    set_seed(config["seed"])

    device = get_device()

    # # parse CLI args
    parser = argparse.ArgumentParser()
    parser.add_argument("--project_root_dir", type=str)
    args = parser.parse_args()

    # override project_root_directory
    if args.project_root_dir:
        config["project_root_dir"] = args.project_root_dir

    root = config["project_root_dir"]
    print(root)

    processed_data_folder = get_processed_folder(config)
    windows_dir = processed_data_folder

    output_dir = f"{processed_data_folder}/dbrl"
    output_path = f"{output_dir}/train_dbrl.pt"

    # -------------------------------------------------------------
    # Load prepared windows
    # -------------------------------------------------------------

    artifact = load_window_artifact(
        windows_dir=windows_dir,
        split="train",
    )

    (
        num_samples,
        window_size,
        num_devices,
    ) = validate_window_artifact(
        artifact
    )

    X = artifact["X"]

    print("Prepared window artifact")
    print(
        f"  X shape          : {X.shape}"
    )

    print(
        f"  y shape          : "
        f"{artifact['y'].shape}"
    )

    print(
        f"  window size      : {window_size}"
    )

    print(
        f"  number of devices: {num_devices}"
    )

    print(
        f"  number of samples: {num_samples}"
    )

    print()

    # -------------------------------------------------------------
    # Convert only X to a torch tensor.
    #
    # y remains in the artifact and is intentionally not passed to
    # DBRL during this standalone forward test.
    # -------------------------------------------------------------

    X_tensor = torch.from_numpy(
        X
    ).float()

    # -------------------------------------------------------------
    # DataLoader
    #
    # shuffle=False is intentional:
    #
    # sample i in the saved representation corresponds exactly to
    # sample i in the prepared window artifact.
    # -------------------------------------------------------------

    dataset = TensorDataset(
        X_tensor,
        torch.zeros(
            X_tensor.size(0),
            dtype=torch.float32,
        ),
    )

    dataloader = DataLoader(
        dataset,
        batch_size=config["hdeg"]["dbrl"]["batch_size"],
        shuffle=False,
        drop_last=False,
    )

    # -------------------------------------------------------------
    # Build DBRL
    # -------------------------------------------------------------

    model = build_dbrl(
        hidden_dim=config["hdeg"]["dbrl"]["hidden_dim"],
        embedding_dim=config["hdeg"]["dbrl"]["embedding_dim"],
        gru_layers=config["hdeg"]["dbrl"]["gru_layers"],
        graph_top_k=config["hdeg"]["dbrl"]["graph_top_k"],
        graph_self_loops=config["hdeg"]["dbrl"]["graph_self_loops"],
        graph_symmetric=config["hdeg"]["dbrl"]["graph_symmetric"],
        graph_heads=config["hdeg"]["dbrl"]["graph_heads"],
        num_devices=num_devices,
    )

    model = model.to(device)

    print("DBRL configuration")
    print(
        f"  hidden_dim       : {config['hdeg']['dbrl']['hidden_dim']}"
    )

    print(
        f"  embedding_dim    : {config['hdeg']['dbrl']['embedding_dim']}"
    )

    print(
        f"  GRU layers       : {config['hdeg']['dbrl']['gru_layers']}"
    )

    print(
        f"  graph_top_k      : {config['hdeg']['dbrl']['graph_top_k']}"
    )

    print(
        f"  graph_self_loops : "
        f"{config['hdeg']['dbrl']['graph_self_loops']}"
    )

    print(
        f"  graph_symmetric  : "
        f"{config['hdeg']['dbrl']['graph_symmetric']}"
    )

    print(
        f"  graph_heads      : {config['hdeg']['dbrl']['graph_heads']}"
    )

    print()

    # -------------------------------------------------------------
    # Run DBRL
    # -------------------------------------------------------------

    print("Running DBRL...")
    print()

    Z = run_dbrl(
        model=model,
        dataloader=dataloader,
        device=device,
        embedding_dim=config["hdeg"]["dbrl"]["embedding_dim"],
        num_devices=num_devices,
        max_batches=config["hdeg"]["dbrl"]["max_batches"],
    )

    # -------------------------------------------------------------
    # Final validation
    # -------------------------------------------------------------

    expected_samples = num_samples

    if (
        config["hdeg"]["dbrl"]["max_batches"] is not None
    ):
        expected_samples = min(
            num_samples,
            config["hdeg"]["dbrl"]["max_batches"] * config["hdeg"]["dbrl"]["batch_size"],
        )

    expected_shape = (
        expected_samples,
        num_devices,
        config["hdeg"]["dbrl"]["embedding_dim"],
    )

    if Z.shape != expected_shape:
        raise RuntimeError(
            "Final DBRL representation shape mismatch. "
            f"Expected {expected_shape}, "
            f"received {tuple(Z.shape)}."
        )

    if not torch.isfinite(Z).all():
        raise RuntimeError(
            "Final DBRL representations contain "
            "NaN or infinite values."
        )

    # -------------------------------------------------------------
    # Statistics
    # -------------------------------------------------------------

    print()
    print("=" * 70)
    print("DBRL forward pass completed")
    print("=" * 70)

    print(
        f"Z shape : {tuple(Z.shape)}"
    )

    print(
        f"Z dtype : {Z.dtype}"
    )

    print(
        f"Z min   : {Z.min().item():.6f}"
    )

    print(
        f"Z max   : {Z.max().item():.6f}"
    )

    print(
        f"Z mean  : {Z.mean().item():.6f}"
    )

    print(
        f"Z std   : {Z.std().item():.6f}"
    )

    print()

    print(
        "[PASS] DBRL input/output shape contract verified."
    )

    print(
        "[PASS] DBRL output contains only finite values."
    )

    # -------------------------------------------------------------
    # Save representations
    # -------------------------------------------------------------

    save_representations(
        output_path=output_path,
        representations=Z,
        split="train",
        window_size=window_size,
        num_devices=num_devices,
        embedding_dim=config["hdeg"]["dbrl"]["embedding_dim"],
        batch_size=config["hdeg"]["dbrl"]["batch_size"],
        seed=config["hdeg"]["dbrl"]["seed"],
        overwrite=config["hdeg"]["dbrl"]["overwrite"],
    )

    print()
    print(
        f"Representations saved to:\n"
        f"  {output_path}"
    )

    print()
    print("=" * 70)
    print("DBRL standalone test finished successfully.")
    print("=" * 70)


if __name__ == "__main__":
    main()